### ISSUE TITLE
Include branch information?

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#141]
Looking at http://resultsdb.ci.centos.org/ccsdb/api/status/7ac01ab175e7ddb7f3e2a9e8d0d1f26a2b953673 I see that the entry was created on ``date_created	"2017-06-01T14:13:32.414641"`` but looking into the git log, I see:
````
commit 7ac01ab175e7ddb7f3e2a9e8d0d1f26a2b953673
...
Date:   Fri Feb 10 05:24:49 2017 +0000
````

This surprises me a little bit, the commit is months old but got into the CI pipeline recently, so I believe it got pushed into a release branch (f26, f25 or f24 since they all seem to be at the same commit now). In order to clear these situation it might be interested to keep the branch of the commit through the pipeline.

Is this doable? Hard to do?

**Comment by p3ck** [comment]
Hi @pypingou, We do know the fedora branch all through the workflow.  It is in the ref field like so: "fedora/${fed_branch}/x86_64/atomic-host"

But we could break it out into a branch field as well.  Should we update the messages to add this?

**Comment by arilivigni** [comment]
The info is there all through the pipeline and is easily accessible
