### ISSUE TITLE
compose.complete not correctly evaluating variable?

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#211]
When looking at the status of https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-a5e4a632-4656-436a-9993-d52cbe10f743&is_raw=true&size=extra-large it looks very much like a variable rather than it's value. Is this a bug or is it intended?

**Comment by scoheb** [comment]
The new Jenkins pipeline 2.0 pipelines will correct this...I believe the message you point to was from the legacy pipelines.

**Comment by pypingou** [comment]
Ok cool.

I'll note that ``compose_rev`` has (or had) the same problem.

**Comment by arilivigni** [comment]
Fixed in future pipeline
