### ISSUE TITLE
compose.running inconsistent branch name

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#213]
When looking at https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-319c899b-a37e-4bb2-ad84-7474066030a3&is_raw=true&size=extra-large the branch used is ``rawhide`` while for compose.complete: https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-f3a0d6ca-d0d1-4d2c-a578-040cbfc9e2b0&is_raw=true&size=extra-large it is the expected ``master``.

Should we fix this?

**Comment by arilivigni** [comment]
Per our documents the branch is correct and in line with what we want to match $fed_branch = master to $branch = rawhide

**Comment by pypingou** [comment]
I'm not seeing a fed_branch there and even if there was one, shouldn't we be consistent between the .running and .complete messages?

**Comment by arilivigni** [comment]
We don't publish that in the message and they are consistent they will be rawhide if the branch is master.  I have seen other fedmsg's do the same for master it is rawhide.

**Comment by pypingou** [comment]
I am confused here, I pointed you to two messages showing two different content and you are telling me they are consistent while I'm showing you they aren't. Do you mean this has been fixed?

You're also telling me about a fed_branch but then saying it's not published. I'm really quite confused here.

**Comment by arilivigni** [comment]
Yes exactly it is fixed.  I also sent you a link to updated messages.

Forget what I said about fed_branch it is just confusingoing you.  Branch will be f2* or rawhide.  As I said before I have seen this in other fedmsgs.
If there is a problem after we are on the product topic I am happy to address it but the messages you point to are very old at this point.

**Comment by pypingou** [comment]
ok, that clears things up, thanks :)
