### ISSUE TITLE
ci.pipeline.compose.test.integration.complete status = TODO ?

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#214]
This may also already be fixed, but in this message: https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-2f33b69b-6336-4e67-98fa-fc17d0a004bc&is_raw=true&size=extra-large the status is set to ``TODO`` while the CI_STATUS is set to ``failed``, is this known?

**Comment by scoheb** [comment]
No trace of **TODO** in the current pipeline code.

**Comment by arilivigni** [comment]
This is old please disregard
