### ISSUE TITLE
Multiple package.running

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#215]
I ran into these three messages:
- https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-7278f217-c941-49a3-a425-a6ba98bcbc8f&is_raw=true&size=extra-large
- https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-3e4ac454-576c-4cf7-a793-5f21210e6b21&is_raw=true&size=extra-large
- https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-b8667659-c498-4fb2-9f83-bce31a7360df&is_raw=true&size=extra-large
Looking at the build_url they seem to correspond to three different builds but they seem to consider the same commit on the same branch.

Is this expected?

**Comment by arilivigni** [comment]
This should not be happening any longer
