### ISSUE TITLE
Message *.running without their corresponding .complete

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#217]
Looking at the recent entries in https://apps.stg.fedoraproject.org/datagrepper/raw?category=ci
I see two compose.running and images.running without their corresponding .complete messages.

Looking at https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-c1b3ca26-c1f3-454a-88ef-7a41f379be46&is_raw=true&size=extra-large (compose.running) and https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-40ca49ec-579d-4204-a4a0-054861a35f56&is_raw=true&size=extra-large (image.running) the repo, commit hash and branch are the same, so I expect the image was created from that compose, but either the .complete message didn't get sent or it didn't reach datagrepper, either one being a bummer.

Could we double-check if something is going on?

**Comment by arilivigni** [comment]
These are old no longer an issue
