### ISSUE TITLE
'message-content' is not serializable 

### ISSUE THREAD

**Issue by BillRainford** [CentOS-PaaS-SIG/ci-pipeline#265]
Downstream CI listens for this fed message from upstream in our pipeline:
org.centos.prod.ci.pipeline.image.test.smoke.complete

One of the fields in the message we receive, 'message-content', has a dash in it and thus is not serializable when we try to parse it and load it as an env variable using the same sort of logic upstream CI does.

It would be good to replace that dash with an underscore or similar. 

This is not really a field we use but others could be hit by that same thing. 

I currently work around this by altering how we parse our fields and replace the dashes with underscores, but it would be better to have the actual message fixed. 

RAW Message body from a org.centos.prod.ci.pipeline.image.test.smoke.complete we received: 

{"CI_TYPE":"custom","build_id":"155","status":"SUCCESS","username":"fedora-atomic","compose_url":"http://artifacts.ci.centos.org/artifacts/fedora-atomic/f26/ostree","rev":"78666125c0f3679f95a1867353ae43ad4b498475","message-content":"","build_url":"https://jenkins-continuous-infra.apps.ci.centos.org/job/ci-pipeline-f26/155/","namespace":"rpms","CI_NAME":"ci-pipeline-f26","image_name":"fedora-atomic-26.229-d7aeb22689b8c7a.qcow2","repo":"kubernetes","compose_rev":"d7aeb22689b8c7a97b0d8ffda64cac15587d869c8052031c3e8d7dd31e528ef1","topic":"org.centos.prod.ci.pipeline.image.test.smoke.complete","image_url":"http://artifacts.ci.centos.org/artifacts/fedora-atomic/f26/images/fedora-atomic-26.229-d7aeb22689b8c7a.qcow2","branch":"f26","type":"qcow2","test_guidance":"''","ref":"fedora/f26/x86_64/atomic-host"}

I talked to Ari about this last week and we both agree this is pretty low pri/impact

**Comment by arilivigni** [comment]
@BillRainford Please submit a PR for this to fix it since this isn't a limitation for the messages we receive.  Also as I stated we don't want to change the plugin we should just change the parsing.  Does that makes sense.  This seems like the cleaner solution and that is how we discussed it.

**Comment by BillRainford** [comment]
@arilivigni OK I created a PR for this. Its a 2 line change.
https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/266

**Comment by arilivigni** [comment]
@BillRainford Thanks https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/266 merged 👍
