### ISSUE TITLE
How long are jobs kept? Where to point users?

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#296]
I opened https://github.com/CentOS-PaaS-SIG/ci-pipeline/issues/287 3 days ago and it points to a job: https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/30/ that is now returning a 404.

This is, however, the link that is present in the messages and sent to the packagers, so this leads to two questions:
- how long are the jobs kept?
- if this url isn't stable, do we have a better one to send the packagers to? So they can see, 3 hours, 2 weeks, a month later why a build didn't pass CI

Thanks

**Comment by arilivigni** [comment]
We keep 50 runs.

This is a Jenkins thing and easily found:
https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/lastSuccessfulBuild/

**Comment by scoheb** [comment]
I might add that the job got renamed due to the fact that we re-created the pipeline with Openshift viewing capabilities. Hence the 404.

**Comment by pypingou** [comment]
So is there a better URL to point the packagers to? I guess 50 builds doesn't last very long.

**Comment by arilivigni** [comment]
We will keep the console log for 90 days
