### ISSUE TITLE
Include the NVR in the pipeline messages

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#297]
In order to integrate the CI results in a way that greenwave and bodhi can use, we would need to store in resultsdb the nvr extracted straight from the spec file.

Potentially this may be as simple as:
````
$ rpmspec -q guake.spec  
guake-0.8.8-3.fc25.noarch
````
(rpmspec is part of rpm-build)

We'll then store this value in resultsdb and when bodhi will ask for the CI results concerning this build greenwave will be able to retrieve them.

Thanks

**Comment by arilivigni** [comment]
Please provide a message example with exactly what you require

**Comment by pypingou** [comment]
I think we probably want to use a new field in the fedmsg messages as this NVR will not be unique (for example when a spec file changes without its NVR being changed)

**Comment by pypingou** [comment]
I guess an entire message may look something like:
````
{
  "username": null, 
  "source_name": "datanommer", 
  "certificate": "LS0tLS1CRUdJTiB....Q0FURS0tLS0tCg==\n", 
  "i": 1, 
  "timestamp": 1503322196.0, 
  "msg_id": "2017-5e9f91cd-bd81-42f4-919d-c05c3a468128", 
  "crypto": "x509", 
  "topic": "org.centos.prod.ci.pipeline.package.complete", 
  "headers": {}, 
  "signature": "O+Lz4/h....dP8=\n", 
  "source_version": "0.8.1", 
 "msg": {
    "CI_TYPE": "custom", 
    "build_id": "85", 
    "username": "fedora-atomic", 
    "rev": "a3e666c78b4ca6c81dc169885d08ecf2b386d10a", 
    "message-content": "", 
    "build_url": "https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/85/", 
    "namespace": "rpms", 
    "CI_NAME": "continuous-infra-ci-pipeline-f26", 
    "repo": "gnutls", 
    "topic": "org.centos.prod.ci.pipeline.package.complete", 
    "status": "SUCCESS", 
    "test_guidance": "''", 
    "branch": "f26", 
    "original_spec_nvr": "gnutls-3.5.15-1.fc26.x86_64.rpm",
    "package_url": "http://artifacts.ci.centos.org/artifacts/fedora-atomic/f26/repo/gnutls_repo/gnutls-3.5.15-1.fc26.246.a3e666c.x86_64.rpm", 
    "ref": "fedora/f26/x86_64/atomic-host"
  }
}
````

I won't fight pro or con the name, ``original_spec_nvr`` has the advantage of specifying it isn't the RPM's nvr but what's in the spec file originally but it's up to you.

Note: we would need to add this field to all the messages (especially the complete ones since those are the most important ones for us).

**Comment by arilivigni** [comment]
I think the original_spec_nvr is fine if that is what you desire it makes no difference to us. 

Does this need to be carried through to all messages?

**Comment by pypingou** [comment]
> Does this need to be carried through to all messages?

All would be great, all the .complete one is pretty much required yes

**Comment by arilivigni** [comment]
gotcha! thanks

**Comment by johnbieren** [comment]
Fixed by https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/298
