### ISSUE TITLE
`No JSON object could be decoded` error in the pipeline

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#350]
Yesterday the pipeline failed due to something that seems to be internal, it happened two times:
- https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/continuous-infra-ci-pipeline-f26/detail/continuous-infra-ci-pipeline-f26/233/pipeline/
- https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/continuous-infra-ci-pipeline-f26/detail/continuous-infra-ci-pipeline-f26/232/pipeline

Is this known?

**Comment by arilivigni** [comment]
infrastructure issue

**Comment by pypingou** [comment]
Do we have a way to detect these and re-trigger the tests?
