### ISSUE TITLE
What does unstable mean?

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#351]
Looking at this pipeline run, it seems to have passed but has been marked as unstable: https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/continuous-infra-ci-pipeline-f26/detail/continuous-infra-ci-pipeline-f26/231/pipeline

what does this mean?

I found this in the logs:
````
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing JUnit
[xUnit] [INFO] - [JUnit] - 2 test report file(s) were found with the pattern '**/logs/ansible_xunit.xml' relative to '/tmp/workspace/continuous-infra-ci-pipeline-f26' for the testing framework 'JUnit'.
[xUnit] [INFO] - Check 'Failed Tests' threshold.
[xUnit] [INFO] - The total number of tests for this category exceeds the specified 'unstable' threshold value.
[xUnit] [INFO] - Setting the build status to UNSTABLE
[xUnit] [INFO] - Stopping recording.
````

but it's not quite helping me.

Any idea?
Thanks :)

**Comment by arilivigni** [comment]
As it states there were test failures so it is unstable.  I think for the pipeline.complete and atomic tests this is a possible status we would get.

**Comment by pypingou** [comment]
So what is the difference between failed and unstable?

**Comment by scoheb** [comment]
Failed could mean there was an infra issue or pipeline problem...unstable means that actual tests from a package failed.
