### ISSUE TITLE
Tests must be invoked with a qcow2 test subject

### ISSUE THREAD

**Issue by stefwalter** [CentOS-PaaS-SIG/ci-pipeline#388]
The tests must be invoked with a test subject, and not a running Atomic Host.

Each change (package or otherwise) composed in the pipeline should prepare a test subject (ie: qcow):

https://fedoraproject.org/wiki/Changes/InvokingTests

The tests are invoked with that test subject, which will then launch and/or consume it as appropriate. Multiple techniques are available to do this, among which might be:

 * Recomposing a qcow2 each time (expensive)
 * Running an ```rpm-ostree rebase``` inside an existing qcow2
 * Running an ```rpm-ostree install``` inside an existing qcow2

**Comment by stefwalter** [comment]
Some partial work on this is done here: https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/383, but as @johnbieren pointed out when looking at that pull request. More work is necessary.

**Comment by arilivigni** [comment]
This is completed:

https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/395
