### ISSUE TITLE
Test output artifacts should be propagated in the fedmsg

### ISSUE THREAD

**Issue by stefwalter** [CentOS-PaaS-SIG/ci-pipeline#389]
The test output artifacts from the tests, produced by the tests themselves, see references to ```$TEST_ARTIFACTS``` and *test artifacts* in the specification should be propagated to other systems consuming the test results. This should likely be a field in the fedmsg.

https://fedoraproject.org/wiki/Changes/InvokingTests

**Comment by arilivigni** [comment]
We already have this via the url and it is in the message:

https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/421/artifact/

12830297-{
12830310-  "i": 1, 
12830408-  "timestamp": 1506975045, 
12830523-  "msg_id": "2017-4566c88e-09be-42a9-8b24-3c5a74db1498", 
12830668-  "crypto": "x509", 
12830776-  "topic": "org.centos.prod.ci.pipeline.complete", 
12830915-  "msgJson": "{\"CI_NAME\":\"continuous-infra-ci-pipeline-f26\",\"CI_TYPE\":\"custom\",\"branch\":\"f26\",\"build_id\":\"421\",\"build_url\":\"https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/421/\",\"compose_rev\":\"a1c75f154ebf755810b3463141324df9a6f9ab47aff4c10a6f57b3d6df445bdd\",\"message-content\":\"\",\"namespace\":\"rpms\",\"nvr\":\"dnsmasq-2.76-4.128.b75bf67.fc26.x86_64\",\"original_spec_nvr\":\"dnsmasq-2.76-4.f26\",\"ref\":\"fedora/f26/x86_64/atomic-host\",\"repo\":\"dnsmasq\",\"rev\":\"b75bf67ab76b97e7676cf2b28b172e8aff49eb3f\",\"status\":\"SUCCESS\",\"test_guidance\":\"''\",\"topic\":\"org.centos.prod.ci.pipeline.complete\",\"username\":\"fedora-atomic\"}", 
12831720-  "msg": {
12831791-    "CI_TYPE": "custom", 
12831904:    "build_id": "421", 
12832015-    "original_spec_nvr": "dnsmasq-2.76-4.f26", 
12832150-    "username": "fedora-atomic", 
12832271-    "nvr": "dnsmasq-2.76-4.128.b75bf67.fc26.x86_64", 
12832412-    "rev": "b75bf67ab76b97e7676cf2b28b172e8aff49eb3f", 
12832555-    "message-content": "", 
12832670-    "build_url": "https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/421/", 
12832872-    "namespace": "rpms", 
12832985-    "CI_NAME": "continuous-infra-ci-pipeline-f26", 
12833124-    "repo": "dnsmasq", 
12833235-    "compose_rev": "a1c75f154ebf755810b3463141324df9a6f9ab47aff4c10a6f57b3d6df445bdd", 
12833410-    "topic": "org.centos.prod.ci.pipeline.complete", 
12833551-    "status": "SUCCESS", 
12833664-    "branch": "f26", 
12833773-    "test_guidance": "''", 
12833888-    "ref": "fedora/f26/x86_64/atomic-host"
12833996-  }
12834022-}
