### ISSUE TITLE
Tests should run from dist-git rather than upstreamfirst

### ISSUE THREAD

**Issue by stefwalter** [CentOS-PaaS-SIG/ci-pipeline#391]
The CI pipeline should be running tests from dist-git proper rather than upstreamfirst.

Some work done here: https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/383

**Comment by johnbieren** [comment]
This should be resolved by https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/397
The tests are now being pulled solely from dist-git
