### ISSUE TITLE
ci.pipeline.complete does not include original_spec_nvr when failing

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#394]
Good Morning,

I was going through some of the ci.pipeline.complete messages this morning and realized that when the message is about a failure, it does not include the ``original_spec_nvr`` field.
Which means we would not be able to link that message to a bodhi udpate.

Some example:
- https://apps.fedoraproject.org/datagrepper/id?id=2017-4b2b9f58-9dc9-4994-8f5e-22eb7aa1244e&is_raw=true&size=extra-large (from this morning)
- https://apps.fedoraproject.org/datagrepper/id?id=2017-a926d1e4-f6f5-4824-9dcb-a7d9b57db9a4&is_raw=true&size=extra-large (from two days ago)

**Comment by arilivigni** [comment]
That is because the RPM build stage failed and didn't get to the point of recording the nvr you could have seen that in the Jenkins link.  I'm not sure there is anything we can do about that?

**Comment by pypingou** [comment]
I thought original_spec_nvr was extracted before that, bummer :s

**Comment by johnbieren** [comment]
In the build in question from this morning, the failure was due to losing connection to the pod. So I don't think it is realistic for any of the data determined in the rpmbuild stage to be there in that case. I can make sure that the original_spec_nvr is added to the logs right at the beginning though (which still would not put it there for a connection lost problem).

**Comment by arilivigni** [comment]
@johnbieren This means it wouldn't get sent out in the message correct in these cases?

**Comment by johnbieren** [comment]
@arilivigni In the cases where we lose connection, I don't think there is anything we can do, so correct. I am just saying I will put it nice and early so if like the build breaks the container or something strange like that, it will be put into the props file as early as can be so *if* the props file is saved, we will have it no matter what.

**Comment by pypingou** [comment]
@johnbieren sounds good to me, thanks :)

**Comment by arilivigni** [comment]
https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/396
