### ISSUE TITLE
The original_spec_nvr field includes the branch name not the dist-tag

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#399]
I was looking at how to display the results of the Atomic CI pipeline in bodhi using ``criu-3.3-5.f26`` as an example since it exists in resultsdb: https://taskotron.fedoraproject.org/resultsdb/results/17377652

I had quite some problem creating the update in my local bodhi update because I was using ``criu-3.3-5.f26`` taken from resultsdb above. But this NVR isn't valid, the proper one is: ``criu-3.3-5.fc26`` (.f*c*26) which is what bodhi knows and queries resultsdb with.

Could we adjust the ``original_spec_nvr`` so it is the dist-tag and not the branch name?

**Comment by arilivigni** [comment]
@johnbieren this should be something easy to tweak.  That being said @pypingou you can also file a PR with the change yourself as well.

**Comment by pypingou** [comment]
Thanks to @johnbieren for taking this :)
