### ISSUE TITLE
config/s2i/create-containers.sh refers to non existing file 

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/ci-pipeline#424]
create_container.sh refers to non existing file
config/s2i/create-containers.sh
https://github.com/CentOS-PaaS-SIG/ci-pipeline/blob/master/config/s2i/create-containers.sh#L6
```
oc create -f rpmbuild/rsync-buildconfig-template.yaml
```
which should be 
```
oc create -f rsync/rsync-buildconfig-template.yaml
```
PR #418 fixes current issue

**Comment by johnbieren** [comment]
This fix is also in https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/425
Note that the rsync template is not the only improper path in that file, the ostree_image_compose one is as well, as that file does not exist until PR 425 adds it.

**Comment by johnbieren** [comment]
Fixed by PR 425
