### ISSUE TITLE
Unstable results appearing as failure

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#506]
So, if I understood #351 correctly, failure in the test suite should appear as 'UNSTABLE' however, it looks like https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/continuous-infra-ci-pipeline-f26/detail/continuous-infra-ci-pipeline-f26/936/pipeline is marked as 'FAILURE' while, afaics, it failed in the test invocation step.

I am reading the information incorrectly?

Thanks :)

**Comment by johnbieren** [comment]
If I am reading it correctly, tests did not actually fail in that build. Instead, standard-test-roles failed during its bring up, seemingly because the copr plugin for dnf wasn't there. I will check out if standard-test-roles should be patched, but because the tests didn't actually run, I don't think anything is wrong here

**Comment by pypingou** [comment]
On Fri, Jan 05, 2018 at 08:10:33AM -0800, Johnny Bieren wrote:
>    If I am reading it correctly, tests did not actually fail in that build.
>    Instead, standard-test-roles failed during its bring up, seemingly because
>    the copr plugin for dnf wasn't there. I will check out if
>    standard-test-roles should be patched, but because the tests didn't
>    actually run, I don't think anything is wrong here

I already reported that issue on the standard-test-role project on pagure so
that should get fixed.
I was just expecting that a failure in the ansible playboo for the test would
result in an error rather than a failure, but I'm ok if we want the way it is.

Thanks for the feedback
