### ISSUE TITLE
Fedora Atomic CI - Fedora 27

### ISSUE THREAD

**Issue by dperpeet** [CentOS-PaaS-SIG/ci-pipeline#508]
I'm not sure I'm reading the config files correctly, but looking at the logs (e.g. for [vim](https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/967/artifact/ci-pipeline-ostree-compose/logs/fedora-atomic-host.json)), it looks like the pipeline is running tests on Fedora Atomic Host 26.

Can we switch this to 27?

**Comment by arilivigni** [comment]
We run them on both f26 and f27 is that a problem?  Should we kill f26?
https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f26/
https://jenkins-continuous-infra.apps.ci.centos.org/job/continuous-infra-ci-pipeline-f27/

**Comment by dperpeet** [comment]
Thanks for the quick reply. I believe testing f26 may be irrelevant now, so we can probably free up the resources. Can you confirm, @pypingou ?

**Comment by dperpeet** [comment]
My reasoning is that this is a developer stream and Fedora 27 is released.

**Comment by dperpeet** [comment]
Considering we're working on testing Fedora 28, this is outdated.
