### ISSUE TITLE
Which host is used to run the all package pipeline

### ISSUE THREAD

**Issue by pypingou** [CentOS-PaaS-SIG/ci-pipeline#547]
Looking at the reason of the last failure (this morning): https://jenkins-continuous-infra.apps.ci.centos.org/view/Fedora%20All%20Packages%20Pipeline/job/upstream-fedora-f27-pipeline/104/console

It seems it fails with:
````
06:42:56 + git checkout -b test_branch
06:42:56 Switched to a new branch 'test_branch'
06:42:56 ++ rpm -q --define 'dist .fc27' --queryformat '%{name}-%{version}-%{release}\n' --specfile php-cs-fixer.spec
06:42:56 ++ head -n 1
06:42:56 error: line 48: Unknown rich dependency op 'with': BuildRequires:  (php-composer(composer/semver)               >= 1.4 with php-composer(composer/semver)               < 2)
06:42:56 error: query of specfile php-cs-fixer.spec failed, can't parse
````

The same command runs fine for me locally (on a F27 box)
````
$ rpm -q --define 'dist .fc27' --queryformat '%{name}-%{version}-%{release}\n' --specfile php-cs-fixer.spec
php-cs-fixer-2.11.0-1.fc27
````

Any idea what could lead to this? Could it be a difference in the underlying OS (F27 vs one that doesn't know reach dependencies?)

**Comment by johnbieren** [comment]
To answer your question, this runs in a f26 container. I will try fixing it

**Comment by arilivigni** [comment]
We are no longer going to run this for f26 anyways so unless it appears in f27, f28, or rawhide we won't be addressing this

**Comment by johnbieren** [comment]
This is due to the container being f26. Must be something only supported in a new version of rpm. I am going to try updating the container and see if anything breaks.

**Comment by johnbieren** [comment]
Fixed in https://github.com/CentOS-PaaS-SIG/ci-pipeline/pull/548
