### ISSUE TITLE
pipeline fails with unknown error

### ISSUE THREAD

**Issue by ignatenkobrain** [CentOS-PaaS-SIG/ci-pipeline#691]
https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/325/pipeline

After 5 minutes looking into the failure I still don't understand it…

**Comment by johnbieren** [comment]
22:52:57 + cat /workDir/workspace/fedora-rawhide-build-pipeline/logs/test.log
22:52:57 FAIL rust/cargo-test

The tests failed, so it failed. It hit some out of space error, as seen by,
java.io.FileNotFoundException: /var/lib/jenkins/jobs/fedora-rawhide-build-pipeline/builds/325/259.log (No space left on device)
so the logs weren't archived properly.
