### ISSUE TITLE
pipeline is broken (no space left on device)

### ISSUE THREAD

**Issue by ignatenkobrain** [CentOS-PaaS-SIG/ci-pipeline#692]
```
hudson.plugins.git.GitException: Command "git config remote.origin.url https://github.com/CentOS-PaaS-SIG/upstream-fedora-pipeline" returned status code 255:
stdout: 
stderr: error: could not lock config file .git/config: No space left on device
```

https://jenkins-continuous-infra.apps.ci.centos.org/view/Fedora%20All%20Packages%20Pipeline/job/fedora-build-pipeline-trigger/lastFailedBuild/

**Comment by johnbieren** [comment]
Jenkins shows there are 11G free on the master. This must have been fixed since this issue was opened. Not sure who fixed it (wasn't me).
